## Testando as features e a classificação


In [1]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import scipy
import parselmouth
import soundfile as sf
import librosa

In [2]:
print("Versão do TensorFlow:", tf.__version__)
print("Versão do NumPy:", np.__version__)
print("Versão do Pandas:", pd.__version__)
print("Versão do librosa:", librosa.__version__)
print("Versão do SciPy:", scipy.__version__)
print("Versão do soundfile:", sf.__version__)


Versão do TensorFlow: 2.12.0
Versão do NumPy: 1.22.4
Versão do Pandas: 1.4.2
Versão do librosa: 0.10.0
Versão do SciPy: 1.10.1
Versão do soundfile: 0.12.1


In [3]:
path_sdl = r'C:\Users\vinic\Documents\datasets\sinais_renomeados_kay\Normal'
path_ptl = r'C:\Users\vinic\Documents\datasets\sinais_renomeados_kay\Paralisia'
path_edm = r'C:\Users\vinic\Documents\datasets\sinais_renomeados_kay\Edema'
path_ndl = r'C:\Users\vinic\Documents\datasets\sinais_renomeados_kay\Nódulo'

In [4]:
path_sdl

'C:\\Users\\vinic\\Documents\\datasets\\sinais_renomeados_kay\\Normal'

### importando biblioteas de features

In [5]:
from feat_ext import get_lpc, get_matrix_cpps, get_matrix_slope

### carregando um sinal saudável

In [6]:
data_sdl, samplerate_sdl = sf.read(path_sdl+'\\normal9.wav')
print(samplerate_sdl)

25000


In [8]:
df_sdl = pd.DataFrame()

In [9]:
media_lpcs_sdl, lpcs_sdl = get_lpc(data_sdl, order = 29)
np.shape(lpcs_sdl)

(291, 29)

In [11]:
filename_sdl = path_sdl+'\\normal9.wav'
cpps_sdl = get_matrix_cpps(filename_sdl, n_frames = np.shape(lpcs_sdl)[0])
np.shape(cpps_sdl)

(291,)

In [12]:
slope_sdl = get_matrix_slope(filename_sdl, n_frames = np.shape(lpcs_sdl)[0])
np.shape(slope_sdl)

(291,)

In [13]:
df_sdl['cpps'] = cpps_sdl
df_sdl['slope'] = slope_sdl
df_sdl

cpps     slope
0    12.870373  5.809944
1    12.870373  5.809944
2    12.870373  5.809944
3    12.870373  5.809944
4    12.870373  5.809944
..         ...       ...
286  12.870373  5.809944
287  12.870373  5.809944
288  12.870373  5.809944
289  12.870373  5.809944
290  12.870373  5.809944

[291 rows x 2 columns]

In [14]:
df_sdl = pd.concat([df_sdl, pd.DataFrame(lpcs_sdl,columns=['lpc1','lpc2',
'lpc3', 'lpc4','lpc5','lpc6','lpc7','lpc8','lpc9','lpc10','lpc11','lpc12','lpc13',
'lpc14','lpc15','lpc16','lpc17','lpc18','lpc19','lpc20','lpc21','lpc22','lpc23',
'lpc24','lpc25','lpc26','lpc27','lpc28','lpc29'])], axis=1)
df_sdl

cpps     slope      lpc1      lpc2      lpc3      lpc4      lpc5  \
0    12.870373  5.809944 -2.018505  1.287484 -0.342385  0.204282  0.070042   
1    12.870373  5.809944 -2.090642  1.559807 -0.768561  0.495505  0.119454   
2    12.870373  5.809944 -1.944814  1.138545 -0.237615  0.085187  0.304451   
3    12.870373  5.809944 -2.009600  1.288071 -0.441554  0.448171 -0.186950   
4    12.870373  5.809944 -1.952616  1.076465 -0.103091  0.104569  0.072813   
..         ...       ...       ...       ...       ...       ...       ...   
286  12.870373  5.809944 -2.039383  1.610307 -1.036775  0.843336 -0.237378   
287  12.870373  5.809944 -1.885117  1.216039 -0.609866  0.528896  0.033812   
288  12.870373  5.809944 -1.953808  1.412053 -0.931465  0.915859 -0.224278   
289  12.870373  5.809944 -2.044373  1.632851 -1.055183  0.791184 -0.125834   
290  12.870373  5.809944 -1.998578  1.503772 -0.928676  0.821343 -0.253278   

         lpc6      lpc7      lpc8  ...     lpc20     lpc21     lpc22  \
0   -0.560863  0.582084 -0.371476  ...  0.143436 -0.303081  0.175278   
1   -0.770119  0.573943  0.003828  ...  0.064526 -0.359166  0.405969   
2   -0.716771  0.461564 -0.132180  ...  0.027800 -0.298297  0.295375   
3   -0.382505  0.346811 -0.019045  ...  0.222365 -0.458981  0.514230   
4   -0.601736  0.623885 -0.223608  ...  0.214921 -0.569523  0.505926   
..        ...       ...       ...  ...       ...       ...       ...   
286 -0.392924  0.334911 -0.124026  ...  0.258569 -0.567647  0.619932   
287 -0.604165  0.296318  0.126494  ...  0.203869 -0.540296  0.574510   
288 -0.649423  0.631124 -0.303664  ...  0.325785 -0.471540  0.468220   
289 -0.440668  0.241167  0.164711  ...  0.275217 -0.524659  0.568467   
290 -0.491064  0.517882 -0.200540  ...  0.445415 -0.707119  0.766614   

        lpc23     lpc24     lpc25     lpc26     lpc27     lpc28     lpc29  
0    0.022537 -0.098849  0.126725 -0.273139  0.020313  0.291590 -0.133779  
1   -0.278716  0.226127 -0.209522 -0.015640 -0.078652  0.289518 -0.124298  
2   -0.098302  0.056308 -0.140106 -0.041198 -0.026400  0.230078 -0.097375  
3   -0.325514  0.120503 -0.042291 -0.131024 -0.001817  0.233777 -0.105209  
4   -0.205866  0.051402 -0.008822 -0.217084  0.037135  0.297571 -0.150004  
..        ...       ...       ...       ...       ...       ...       ...  
286 -0.506831  0.392444 -0.310689  0.071172 -0.088670  0.211336 -0.077076  
287 -0.295908  0.118191 -0.152239 -0.004371 -0.043495  0.192424 -0.070181  
288 -0.173323 -0.097386  0.088832 -0.185228  0.149310  0.017455 -0.009086  
289 -0.407919  0.162465 -0.031325 -0.109318  0.008372  0.144568 -0.051314  
290 -0.544289  0.267774 -0.162763 -0.024651 -0.003581  0.150565 -0.061287  

[291 rows x 31 columns]

In [15]:
numeric_feature_names_sdl = ['cpps', 'slope','lpc1',  'lpc2',
                         'lpc3', 'lpc4', 'lpc5', 'lpc6',
                         'lpc7', 'lpc8','lpc9', 'lpc10',
                         'lpc11', 'lpc12']
numeric_features_sdl = df_sdl[numeric_feature_names_sdl]
numeric_features_sdl.head()

cpps     slope      lpc1      lpc2      lpc3      lpc4      lpc5  \
0  12.870373  5.809944 -2.018505  1.287484 -0.342385  0.204282  0.070042   
1  12.870373  5.809944 -2.090642  1.559807 -0.768561  0.495505  0.119454   
2  12.870373  5.809944 -1.944814  1.138545 -0.237615  0.085187  0.304451   
3  12.870373  5.809944 -2.009600  1.288071 -0.441554  0.448171 -0.186950   
4  12.870373  5.809944 -1.952616  1.076465 -0.103091  0.104569  0.072813   

       lpc6      lpc7      lpc8      lpc9     lpc10     lpc11     lpc12  
0 -0.560863  0.582084 -0.371476  0.895842 -1.042143  0.514437 -0.492192  
1 -0.770119  0.573943  0.003828  0.349858 -0.644220  0.459280 -0.812857  
2 -0.716771  0.461564 -0.132180  0.751635 -0.884279  0.244865 -0.299268  
3 -0.382505  0.346811 -0.019045  0.646699 -1.073657  0.755939 -0.902332  
4 -0.601736  0.623885 -0.223608  0.610484 -0.896644  0.603164 -0.699603

In [16]:
# convertendo features para TENSOR
tf.convert_to_tensor(numeric_features_sdl)

<tf.Tensor: shape=(291, 14), dtype=float64, numpy=
array([[12.87037314,  5.80994399, -2.01850537, ..., -1.0421428 ,
         0.51443708, -0.49219241],
       [12.87037314,  5.80994399, -2.09064232, ..., -0.64421962,
         0.45928025, -0.81285727],
       [12.87037314,  5.80994399, -1.9448139 , ..., -0.88427873,
         0.24486483, -0.29926835],
       ...,
       [12.87037314,  5.80994399, -1.95380796, ..., -1.16713177,
         0.70813988, -0.83829229],
       [12.87037314,  5.80994399, -2.04437272, ..., -0.49857185,
         0.29927867, -0.60401209],
       [12.87037314,  5.80994399, -1.99857796, ..., -1.09336053,
         0.90469426, -1.19548555]])>

In [17]:
# Aplicando normalização das features (para equalizar grandezas)
normalizer_sdl = tf.keras.layers.Normalization(axis=-1)
normalizer_sdl.adapt(numeric_features_sdl)

In [18]:
# verificando normalização
normalizer_sdl(numeric_features_sdl.iloc[:3])

<tf.Tensor: shape=(3, 14), dtype=float32, numpy=
array([[-0.9265026 ,  0.        , -0.39143172, -0.19921911,  0.77502114,
        -0.78355145, -0.06062435,  0.58909404,  0.08701133, -1.2542217 ,
         1.4896903 , -0.8250831 , -0.09343917,  0.9133203 ],
       [-0.9265026 ,  0.        , -1.3454375 ,  1.3167232 , -1.0107996 ,
         0.42123738,  0.13409692, -0.21394183,  0.05412014,  0.38524964,
        -1.0222762 ,  1.0974646 , -0.34942776, -0.55228436],
       [-0.9265026 ,  0.        ,  0.58313376, -1.0283154 ,  1.2140455 ,
        -1.2762485 ,  0.86313426, -0.00921628, -0.3999062 , -0.20888752,
         0.826219  , -0.0623701 , -1.3445522 ,  1.7950834 ]],
      dtype=float32)>

In [21]:
caminho_modelo = r'C:\Users\vinic\Documents\IFPB\Arquitetura\proj-arquit\modelo'

In [22]:
# checando o diretório
os.listdir(caminho_modelo)

['project_model.h5']

In [23]:
# Carregue o modelo
modelo_carregado = tf.keras.models.load_model(caminho_modelo+'\\project_model.h5')

In [24]:
modelo_carregado.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                150       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 5)                 55        
                                                                 
 dense_3 (Dense)             (None, 1)                 6         
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [25]:
# Testando como seria a PREDIÇÃO DA CLASSE
predictions = modelo_carregado.predict(numeric_features_sdl)
predicted_classes = (predictions > 0.5).astype(int)
print(predicted_classes)

print(len(predicted_classes == 1))
print(len(predicted_classes == 0))

10/10 [==============================] - 0s 2ms/step
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [

In [31]:
pred_vec = np.reshape(predicted_classes, len(predicted_classes))
pred_vec 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [32]:
contagem = np.bincount(pred_vec)
contagem

array([291], dtype=int64)

In [35]:
contagem.shape

(1,)

In [36]:
def get_prob(predictions_vector):
  '''
  Esta função pega as predições e retorna a probabilidade
  de o paciente ter uma condição patológica
  '''
  pred_vec = np.reshape(predictions_vector, len(predictions_vector))
  contagem = np.bincount(pred_vec)

  if len(contagem.shape) > 1:
    prob_sdl = ( contagem[0] / len(pred_vec)) * 100
    prob_ptl = ( contagem[1] / len(pred_vec)) * 100
  elif len(contagem.shape) ==1:
    if pred_vec[0] == 0:
      prob_sdl = 100
      prob_ptl = 0
    else:
      prob_sdl = 0
      prob_ptl = 100

  else:
    pass

  

  return prob_sdl , prob_ptl


In [37]:
sdl_p , ptl_p = get_prob(predicted_classes)
print(f"Probabilidade de ter patologia: {ptl_p:.2f} %")
print(f"Probabilidade de ter saúde: {sdl_p:.2f} %")

Probabilidade de ter patologia: 0.00 %
Probabilidade de ter saúde: 100.00 %


In [46]:
#path_sinal = r'D:\Documentos_HDD\013_postdocIFPB\Engenharia Elétrica-vozes\Fernando\fabav2.wav'
path_sinal = r'C:\Users\vinic\Documents\datasets\sinais_renomeados_kay\Normal\normal19.wav'


In [51]:
import parselmouth
from scipy.io.wavfile import read
import numpy as np
from audio_format import pcm2float
from scipy.io import wavfile

rate, signal = wavfile.read(path_sinal)
# sndG é o sinal convertido para float32
sndG = pcm2float(signal)
# sndPraat é o float32 no formato da biblioteca do Praat
sndPraat = parselmouth.Sound(sndG)
np.shape(sndPraat)

(1, 75000)

In [48]:
len(np.shape(sndPraat))

2

In [49]:
if len(np.shape(sndPraat)) > 1:
    if np.shape(sndPraat)[0] > np.shape(sndPraat)[1]:
        sndPraat = np.mean(sndPraat, axis=1)
    else:
        sndPraat = np.mean(sndPraat, axis=0)

len(sndPraat)

75000

In [52]:
if len(np.shape(sndPraat)) > 1:
    sndPraat = np.mean(sndPraat, axis=1)

len(sndPraat)

1